#!/bin/bash
mkdir /home/pi/RetroPie/savestates
mkdir /home/pi/RetroPie/savefiles
mkdir /home/pi/RetroPie/savefiles/sega32x
mkdir /home/pi/RetroPie/savefiles/wonderswan
mkdir /home/pi/RetroPie/savefiles/atari5200
mkdir /home/pi/RetroPie/savefiles/ngp
mkdir /home/pi/RetroPie/savefiles/n64
mkdir /home/pi/RetroPie/savefiles/pcengine
mkdir /home/pi/RetroPie/savefiles/wonderswancolor
mkdir /home/pi/RetroPie/savefiles/ngpc
mkdir /home/pi/RetroPie/savefiles/virtualboy
mkdir /home/pi/RetroPie/savefiles/fds
mkdir /home/pi/RetroPie/savefiles/arcade
mkdir /home/pi/RetroPie/savefiles/atari7800
mkdir /home/pi/RetroPie/savefiles/snes
mkdir /home/pi/RetroPie/savefiles/neogeo
mkdir /home/pi/RetroPie/savefiles/megadrive
mkdir /home/pi/RetroPie/savefiles/atari2600
mkdir /home/pi/RetroPie/savefiles/supergrafx
mkdir /home/pi/RetroPie/savefiles/mastersystem
mkdir /home/pi/RetroPie/savefiles/msx
mkdir /home/pi/RetroPie/savefiles/ports
mkdir /home/pi/RetroPie/savefiles/ports/doom
mkdir /home/pi/RetroPie/savefiles/ports/quake
mkdir /home/pi/RetroPie/savefiles/atarilynx
mkdir /home/pi/RetroPie/savefiles/gba
mkdir /home/pi/RetroPie/savefiles/psx
mkdir /home/pi/RetroPie/savefiles/pce-cd
mkdir /home/pi/RetroPie/savefiles/gbc
mkdir /home/pi/RetroPie/savefiles/segacd
mkdir /home/pi/RetroPie/savefiles/nes
mkdir /home/pi/RetroPie/savefiles/gamegear
mkdir /home/pi/RetroPie/savefiles/gb
mkdir /home/pi/RetroPie/savestates/sega32x
mkdir /home/pi/RetroPie/savestates/wonderswan
mkdir /home/pi/RetroPie/savestates/atari5200
mkdir /home/pi/RetroPie/savestates/ngp
mkdir /home/pi/RetroPie/savestates/n64
mkdir /home/pi/RetroPie/savestates/pcengine
mkdir /home/pi/RetroPie/savestates/wonderswancolor
mkdir /home/pi/RetroPie/savestates/ngpc
mkdir /home/pi/RetroPie/savestates/virtualboy
mkdir /home/pi/RetroPie/savestates/fds
mkdir /home/pi/RetroPie/savestates/arcade
mkdir /home/pi/RetroPie/savestates/atari7800
mkdir /home/pi/RetroPie/savestates/snes
mkdir /home/pi/RetroPie/savestates/neogeo
mkdir /home/pi/RetroPie/savestates/megadrive
mkdir /home/pi/RetroPie/savestates/atari2600
mkdir /home/pi/RetroPie/savestates/supergrafx
mkdir /home/pi/RetroPie/savestates/mastersystem
mkdir /home/pi/RetroPie/savestates/msx
mkdir /home/pi/RetroPie/savestates/ports
mkdir /home/pi/RetroPie/savestates/ports/doom
mkdir /home/pi/RetroPie/savestates/ports/quake
mkdir /home/pi/RetroPie/savestates/atarilynx
mkdir /home/pi/RetroPie/savestates/gba
mkdir /home/pi/RetroPie/savestates/psx
mkdir /home/pi/RetroPie/savestates/pce-cd
mkdir /home/pi/RetroPie/savestates/gbc
mkdir /home/pi/RetroPie/savestates/segacd
mkdir /home/pi/RetroPie/savestates/nes
mkdir /home/pi/RetroPie/savestates/gamegear
mkdir /home/pi/RetroPie/savestates/gb
